---
ActionAtoms:
  backward:
    ui_accessibilityId: 返回上一级
    ui_action: click

  backward in webview:
    ui_accessibilityId: web返回上一级
    ui_action: click

  close webview:
    ui_name: 关闭
    ui_action: click

  return homepage:
    ui_accessibilityId: 回到首页
    ui_action: click

  swipe down:
    ui_action: swipe
    data:
      sxRatio: 0.5
      syRatio: 0.8
      exRatio: 0.5
      eyRatio: 0.1
      duration: 400

  get orderId:
    ui_xpath: //XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeCell[4]/XCUIElementTypeStaticText[5]
    ui_action: getValue

  fake pay:
    ui_action: net
    data:
      url: http://shopappserver.showjoy.net/Fake_Pay
      qs:
        orderNumber: ${idid}
        identify: ${x_request}
      headers:
        cookie: ${ticket}

